version: "3.8"

services:
    mysql:
        container_name: mysql
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    adminer:
        container_name: adminer
        image: adminer
        ports:
            - "8090:8080"
        environment:
            ADMINER_DEFAULT_SERVER: mysql

    laravel:
        container_name: laravel
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - mysql
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: root
            DB_PASSWORD: ${DB_PASSWORD}
        command: bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"

volumes:
    mysql_data:
